/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.CombatResult;
import NapakalakiGame.Napakalaki;
/**
 *
 * @author easynote
 */
public class NapakalakiView extends javax.swing.JFrame {
    Napakalaki napakalakiModel;

    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
        monsterView1.setVisible(false);
        combat.setEnabled(false);
    }
    
    public void setNapakalaki(Napakalaki n){
        napakalakiModel = n;
        
        monsterView1.setMonster(n.getCurrentMonster());
        playerView1.setPlayer(n.getCurrentPlayer());
        playerView1.setNapakalakiM(napakalakiModel);
        next_turn.setEnabled(false);
        
        repaint();
    }
    
    Napakalaki getNapakalaki(){
        return napakalakiModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        meet_monster = new javax.swing.JButton();
        combat = new javax.swing.JButton();
        next_turn = new javax.swing.JButton();
        playerView1 = new GUI.PlayerView();
        monsterView1 = new GUI.MonsterView();
        estado_juego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        meet_monster.setText("Meet the monster");
        meet_monster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meet_monsterActionPerformed(evt);
            }
        });

        combat.setText("Combat");
        combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatActionPerformed(evt);
            }
        });

        next_turn.setText("Next turn");
        next_turn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_turnActionPerformed(evt);
            }
        });

        estado_juego.setText("Estado juego");
        estado_juego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado_juegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(meet_monster)
                    .addComponent(next_turn)
                    .addComponent(combat)
                    .addComponent(estado_juego))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(meet_monster)
                        .addGap(18, 18, 18)
                        .addComponent(combat)
                        .addGap(18, 18, 18)
                        .addComponent(next_turn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(estado_juego)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatActionPerformed
        CombatResult r = napakalakiModel.developCombat();
        if (CombatResult.WIN == r)
            playerView1.makeVisible(true);
        playerView1.discardAllTreasures(true);
        playerView1.discardTreasures(true);
        setNapakalaki(napakalakiModel);
        next_turn.setEnabled(true);
        combat.setEnabled(false);
    }//GEN-LAST:event_combatActionPerformed

    private void meet_monsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meet_monsterActionPerformed
        monsterView1.setVisible(true);
        meet_monster.setEnabled(false);
        playerView1.makeVisible(false);
        playerView1.discardTreasures(false);
        playerView1.discardAllTreasures(false);
        combat.setEnabled(true);
    }//GEN-LAST:event_meet_monsterActionPerformed

    private void next_turnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_turnActionPerformed
        if (napakalakiModel.nextTurn()){
            setNapakalaki(napakalakiModel);
            monsterView1.setVisible(false);
            meet_monster.setEnabled(true);
            next_turn.setEnabled(false);
            playerView1.pendingBadConsequence(false);
            playerView1.makeVisible(true);
        }
    }//GEN-LAST:event_next_turnActionPerformed

    private void estado_juegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado_juegoActionPerformed
        EstadoJuego ej = new EstadoJuego(this,true);
        ej.getEstado();
    }//GEN-LAST:event_estado_juegoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combat;
    private javax.swing.JButton estado_juego;
    private javax.swing.JButton meet_monster;
    private GUI.MonsterView monsterView1;
    private javax.swing.JButton next_turn;
    private GUI.PlayerView playerView1;
    // End of variables declaration//GEN-END:variables
}
