/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.CultistPlayer;
import NapakalakiGame.Napakalaki;
import NapakalakiGame.Player;
import NapakalakiGame.PlayerCorpulento;
import NapakalakiGame.PlayerCuadrupedo;
import NapakalakiGame.Treasure;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author easynote
 */
public class PlayerView extends javax.swing.JPanel {
    Player playerModel;
    Napakalaki napakalakiModel;
    Boolean canConvert = true;
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
        pendingBadConsequenceView2.setVisible(false);
    }
    
    private void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) {
        aPanel.removeAll();
        for (Treasure t : aList) {
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure (t);
            aTreasureView.setVisible (true);
            aPanel.add (aTreasureView);
        }
        aPanel.repaint();
        aPanel.revalidate();
    }

    public void setNapakalakiM(Napakalaki n){
        napakalakiModel = n;
    }
    
    void makeVisible(Boolean b){
        make_visible.setEnabled(b);
    }
    
    void discardTreasures(Boolean b){
        discard_treasures.setEnabled(b);
    }
    
    void discardAllTreasures(Boolean b){
        discard_all_treasures.setEnabled(b);
    }
    
    void pendingBadConsequence(Boolean b){
        pendingBadConsequenceView2.setVisible(b);
    }
    
    public void setPlayer(Player p){
        playerModel = p;
        this.name.setText(p.getName());
        this.level.setText("Level " + Integer.toString(p.getLevels()));
        
        if (p instanceof CultistPlayer)
            this.type.setText("Sectario");
        else
            if (p instanceof PlayerCorpulento)
                this.type.setText("Player Corpulento");
            else
                if (p instanceof PlayerCuadrupedo)
                    this.type.setText("Player Cuadrúpedo");
                else
                    this.type.setText("No sectario");
        
        this.fillTreasurePanel(visibleTreasures, p.getVisibleTreasures());
        this.fillTreasurePanel(hiddenTreasures, p.getHiddenTreasures());
        
        if (!playerModel.validState()){
            pendingBadConsequenceView2.setPendingBadConsequence(playerModel.getPendingBadConsequence());
            pendingBadConsequenceView2.setVisible(true);
        }
        
        repaint();
        revalidate();
    }
    
    private ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) {
        // Se recorren los tesoros que contiene el panel,
        //almacenando en un vector aquellos que están seleccionados.
        //Finalmente se devuelve dicho vector.
        TreasureView tv;
        ArrayList<Treasure> output = new ArrayList();
        for (Component c : aPanel.getComponents()) {
            tv = (TreasureView) c;
            if ( tv.isSelected() )
                output.add ( tv.getTreasure() );
        }
        return output;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        hiddenTreasures = new javax.swing.JPanel();
        make_visible = new javax.swing.JButton();
        discard_treasures = new javax.swing.JButton();
        discard_all_treasures = new javax.swing.JButton();
        pendingBadConsequenceView2 = new GUI.PendingBadConsequenceView();
        visibleTreasures = new javax.swing.JPanel();
        PlayerCorpulento = new javax.swing.JButton();
        PlayerCuadrupedo = new javax.swing.JButton();

        name.setText("Nombre");

        level.setText("Nivel");

        type.setText("Type");

        hiddenTreasures.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        make_visible.setText("Make visible");
        make_visible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                make_visibleActionPerformed(evt);
            }
        });

        discard_treasures.setText("Discard treasures");
        discard_treasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discard_treasuresActionPerformed(evt);
            }
        });

        discard_all_treasures.setText("Discard all treasures");
        discard_all_treasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discard_all_treasuresActionPerformed(evt);
            }
        });

        visibleTreasures.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        visibleTreasures.setLayout(new javax.swing.BoxLayout(visibleTreasures, javax.swing.BoxLayout.LINE_AXIS));

        PlayerCorpulento.setText("PlayerCorpulento");
        PlayerCorpulento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerCorpulentoActionPerformed(evt);
            }
        });

        PlayerCuadrupedo.setText("PlayerCuadrupedo");
        PlayerCuadrupedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerCuadrupedoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(make_visible)
                                .addGap(18, 18, 18)
                                .addComponent(discard_treasures)
                                .addGap(18, 18, 18)
                                .addComponent(discard_all_treasures))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PlayerCorpulento)
                                .addGap(40, 40, 40)
                                .addComponent(PlayerCuadrupedo)))
                        .addGap(32, 32, 32)
                        .addComponent(pendingBadConsequenceView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 116, Short.MAX_VALUE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hiddenTreasures, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(visibleTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(level)
                    .addComponent(type))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discard_all_treasures)
                            .addComponent(discard_treasures)
                            .addComponent(make_visible))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PlayerCorpulento)
                            .addComponent(PlayerCuadrupedo))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(pendingBadConsequenceView2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void make_visibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_make_visibleActionPerformed
        ArrayList<Treasure> selHidden = getSelectedTreasures (hiddenTreasures);
        napakalakiModel.makeTreasuresVisible (selHidden);
        setPlayer (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_make_visibleActionPerformed

    private void discard_treasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discard_treasuresActionPerformed
        ArrayList<Treasure> selVisible = getSelectedTreasures(visibleTreasures);
        ArrayList<Treasure> selHidden = getSelectedTreasures(hiddenTreasures);
        napakalakiModel.discardHiddenTreasures(selHidden);
        napakalakiModel.discardVisibleTreasures(selVisible);
        
        setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_discard_treasuresActionPerformed

    private void discard_all_treasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discard_all_treasuresActionPerformed
        playerModel.discardAllTreasures();
        
        setPlayer(playerModel);
    }//GEN-LAST:event_discard_all_treasuresActionPerformed
//EXAMEN
    private void PlayerCorpulentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerCorpulentoActionPerformed
        if ((playerModel instanceof CultistPlayer) == false && canConvert){
            PlayerCorpulento p = new PlayerCorpulento(playerModel);
            napakalakiModel.convertTo(p);
            canConvert = false;

            setPlayer(napakalakiModel.getCurrentPlayer());
        }
    }//GEN-LAST:event_PlayerCorpulentoActionPerformed

    private void PlayerCuadrupedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerCuadrupedoActionPerformed
        if ((playerModel instanceof CultistPlayer) == false && canConvert){
            PlayerCuadrupedo p = new PlayerCuadrupedo(playerModel);
            napakalakiModel.convertTo(p);
            canConvert = false;
            
            setPlayer(napakalakiModel.getCurrentPlayer());
        }
    }//GEN-LAST:event_PlayerCuadrupedoActionPerformed
//FINEXAMEN

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlayerCorpulento;
    private javax.swing.JButton PlayerCuadrupedo;
    private javax.swing.JButton discard_all_treasures;
    private javax.swing.JButton discard_treasures;
    private javax.swing.JPanel hiddenTreasures;
    private javax.swing.JLabel level;
    private javax.swing.JButton make_visible;
    private javax.swing.JLabel name;
    private GUI.PendingBadConsequenceView pendingBadConsequenceView2;
    private javax.swing.JLabel type;
    private javax.swing.JPanel visibleTreasures;
    // End of variables declaration//GEN-END:variables
}
